# Generated by Django 6.0.1 on 2026-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_usermodel_u_password_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
