# Generated by Django 6.0.1 on 2026-01-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_usermodel_u_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=150)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_description', models.TextField()),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('p_stock', models.IntegerField(default=0)),
                ('p_avail', models.BooleanField(default=True)),
                ('p_created', models.DateTimeField(auto_now_add=True)),
                ('p_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.category')),
            ],
        ),
    ]
