# Generated by Django 6.0.1 on 2026-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='c_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
