# Generated by Django 6.0.1 on 2026-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_category_c_created_category_c_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_avail',
            field=models.BooleanField(default=False),
        ),
    ]
