# Generated by Django 6.0.1 on 2026-01-31 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_product_p_avail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_quanity', models.IntegerField(default=1)),
                ('c_created', models.DateTimeField(auto_now_add=True)),
                ('c_updated', models.DateTimeField(auto_now=True)),
                ('c_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
