# Generated by Django 6.0.1 on 2026-01-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='c_quanity',
            new_name='c_quantity',
        ),
    ]
