# Generated by Django 6.0.1 on 2026-01-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_c_quanity_cartmodel_c_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='c_user',
        ),
    ]
