# Generated by Django 6.0.1 on 2026-02-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_cartmodel_c_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
