# Generated by Django 6.0.1 on 2026-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='cart_placed',
            field=models.BooleanField(default=True),
        ),
    ]
