# Generated by Django 6.0.1 on 2026-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_cartmodel_cart_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_placed',
            field=models.BooleanField(default=False),
        ),
    ]
