# Generated by Django 6.0.1 on 2026-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_ordermodel_foodtrackingmodel_paymentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='order_number',
            field=models.CharField(default='999999999', max_length=200),
        ),
    ]
